### ISSUE TITLE
Existing cluster seen as "new" upon subsequent terraform apply

### ISSUE THREAD

**Issue by jshrack-ssi** [rancher/terraform-provider-rke#163] opened 2020-02-04 20:30 UTC
I've come across some interesting (annoying) behavior when applying a plan update to a pre-existing RKE cluster. The initial apply did not complete to the end, I then added an IAM policy to an existing worker node rule, and the plan subsequently asserted a whole new cluster. Any attempt to apply that configuration fails with a api health check validation error. There have been no changes at all to the RKE cluster template, only the IAM role/policy association. This is using the 1.0.0-rc1 rke provider with PR#150 merged.

**Comment by rawmind0** [comment] 2020-02-04 21:14
Could you please explain step by step how to reproduce the issue??

**Comment by jshrack-ssi** [comment] 2020-02-04 21:20
That's going to be a bit difficult... There's a sizeable plan that underlies our Rancher Management Server construct. I'll give it a go... 

1) Apply first plan. Plan fails at whatever helm chart release due to IAM permissions. RKE cluster is up and operational at this point.
2) Modify plan to add new IAM policy attachment to existing worker node instance role.
3) Apply updated plan. 
4) Results in new plan results in creation of a "new" cluster despite the fact a cluster already exists. No other changes have been made to the RKE cluster plan itself.

It's as though the state of the existing cluster is entirely ignored or has been blown away. If there are specific files or support information I can provide happy to do so.

**Comment by rawmind0** [comment] 2020-02-04 21:46
Thanks for the update. As i understand, your plan is not failing due to this provider, is it?? If your first plan fails, probably rke cluster data is not saved to tfstate, may be related with #152.  This should be addressed with PR #152

**Comment by jshrack-ssi** [comment] 2020-02-04 22:42
I think the rke provider is being impacted perhaps by #152. I was actually going to merge this change as well suspecting it might be related. I will try that and see if that takes care of the problem.

**Comment by rawmind0** [comment] 2020-02-05 23:59
PR #161 is already merged. Please, reopen issue if needed

**Closed by rawmind0** 2020-02-05 23:59 UTC
