### ISSUE TITLE
Disaster recovery

### ISSUE THREAD

**Issue by ajfriesen** [rancher/terraform-provider-rke#62] opened 2019-02-20 15:51 UTC
# Basic Setup

We setup 3 instances on aws in different AZ.
This 3 instances work as rancher nodes in a private subnet with fixed ips.
We have a bastion host to connect to this private host.
We also expose the kubernetes API to run kubectl and helm from my local machine, if we want to.
We also run the rke provider to setup the rancher management cluster.

Additionally we also deploy cert-manager and rancher-ui via the helm provider.

Everything is fine.

Here is the basic setup for rke:

```yaml

resource rke_cluster "rancher_cluster" {

  cluster_name = "rancher-management"

  bastion_host = {
    address      = "${aws_instance.rancher_bastion_instance.public_ip}"
    user         = "ubuntu"
    ssh_key      = "${file("~/.ssh/rancher.pem")}"
    port         = 22
  }

  authentication {
    strategy = "x509"

    sans = [
      "${aws_lb.rancher_nlb.dns_name}",
    ]
  }

  nodes = [
    {
      address = "${aws_instance.rancher_node_1.private_ip}"
      user    = "ubuntu"
      //TODO: Modify this when we integrate the vault. For now it expects the rancher key to be in the .ssh folder.
      ssh_key = "${file("~/.ssh/rancher.pem")}"
      role    = ["controlplane", "worker", "etcd"]
    },
    {
      address = "${aws_instance.rancher_node_2.private_ip}"
      user    = "ubuntu"
      //TODO: Modify this when we integrate the vault. For now it expects the rancher key to be in the .ssh folder.
      ssh_key = "${file("~/.ssh/rancher.pem")}"
      role    = ["controlplane", "worker", "etcd"]
    },
    {
      address = "${aws_instance.rancher_node_3.private_ip}"
      user    = "ubuntu"
      //TODO: Modify this when we integrate the vault. For now it expects the rancher key to be in the .ssh folder.
      ssh_key = "${file("~/.ssh/rancher.pem")}"
      role    = ["controlplane", "worker", "etcd"]
    }
  ]
}

resource "local_file" "kube_cluster_yaml" {
  filename = "${path.root}/kubeconfig_rancher_cluster.yaml"
  content = "${rke_cluster.rancher_cluster.kube_config_yaml}"
}
```

# Incident

For science and my inner chaos monkey I just terminated one of the instances via the aws console.
Rancher says: ```Kubelet stopped posting node status.```

When we ```terraform apply``` again a new instance is created with the same IP it had before.
But the instance never will join the rke cluster.

# Question

How shall we proceed when we loose a node for whatever reason?
I would think that a terraform apply should solve issue.

Since in my opinion  a new instance will be created and also a new instance for the rke cluster should be spinned up with rke.

**Comment by yamamoto-febc** [comment] 2019-03-05 02:18
Hi @ajfriesen, Thank you for detailed report!

I think it is expected behavior by terraform.

The value of the attributes of `rke_cluster` is not changed when the instance is recreated.
(Because there IP address has not been changed)
Therefore, rke_cluster will not be updated or recreated.

But it is not good...  I want to find out a good way.  
If you have good idea, please let me know!

**Comment by ajfriesen** [comment] 2019-03-05 22:14
When I first delete a node and then run terraform apply again a new node is created.
The new nodes never gets into the rancher rke cluster.

Maybe this is trough the host key validation?

The new node will get the same and static IP and  the bastion host still will maybe get the host key validation error.

I need to check if this will work when I deactivate host key checking on the bastion host.
If this is the wrong route let me know.

**Comment by ajfriesen** [comment] 2019-03-12 16:57
As you already state, this has nothing to do with the host key verification.

Today we tried this disaster recovery.
We could workaround that, when we gave one of the rancher nodes a different IP Adress and then reapplied terraform again.

Is it possible to store the instance-id by aws instead of the private ip as something in you terraform state in rke_cluster?

**Comment by Troyhy** [comment] 2019-08-19 10:34
I have similar issue when testing in Hetzner cloud. My setup is adaptation of DO example.
Steps:
* Initial creation of cluster went fine. 1 etcd/control plane -node, 1 worker -node
* removed node from hetzner console.
* rerun `terraform apply`, witch noticed that node is missing.
* new node recycled the ip of old node, rke does not update.

**Comment by rawmind0** [comment] 2020-03-31 13:44
If nothing is changing on nodes argument, the rke cluster is unable to know that an update is needed. Please, take a look to [this comment](https://github.com/rancher/terraform-provider-rke/issues/108#issuecomment-534470983)

Duplicated, closing in favour of #108 . Please, reopen issue if needed

**Closed by rawmind0** 2020-03-31 13:44 UTC
Labels: duplicate
