### ISSUE TITLE
Cluster is always updated in v1.0.0-rc5

### ISSUE THREAD

**Issue by NeinsKnull** [rancher/terraform-provider-rke#188] opened 2020-04-06 16:57 UTC
Version: v1.0.0-rc5

terraform apply shows me always 

``` rke_cluster.cluster will be updated in-place ```

because the following fields are always marked for update:

```bastion_host {
            address        = "XXXXXX"
            port           = "XX"
            ssh_agent_auth = XXXX
            ssh_key        = (sensitive value)
          - ssh_key_path   = "~/.ssh/id_rsa" -> null
            user           = "XXX"
        }
```

and

```- upgrade_strategy {
          - drain                        = false -> null
          - max_unavailable_controlplane = "1" -> null
          - max_unavailable_worker       = "10%" -> null 
```

**Comment by rawmind0** [comment] 2020-04-09 12:46
False diff on `upgrade_strategy` should be fixed with PR #191 .

Unable to reproduce  `ssh_key_path` diff, could you provide your tf file??

**Comment by NeinsKnull** [comment] 2020-04-09 13:22
I cut the block name sorry. The ssh_key_path diff takes place on bastion_host block:
`...
      ~ bastion_host {
            address        = "*******"
            port           = "*****"
            ssh_agent_auth = false
            ssh_key        = (sensitive value)
          - ssh_key_path   = "~/.ssh/id_rsa" -> null
            user           = "*******"
        }
...`

**Comment by rawmind0** [comment] 2020-04-09 13:40
Ok, updated PR to fix both.

**Comment by jmiracle43** [comment] 2020-04-09 16:44
I show it as always wanting to change the following blocks in a dev cluster as well:
```
      ~ cluster_cidr              = "172.20.0.0/16" -> (known after apply)
      ~ cluster_dns_server        = "172.21.0.10" -> (known after apply)
      ~ cluster_domain            = "cluster.local" -> (known after apply)

              - audit_log {
                  - enabled = true -> null

                  - configuration {
                      - format     = "json" -> null
                      - max_age    = 30 -> null
                      - max_backup = 10 -> null
                      - max_size   = 100 -> null
                      - path       = "/var/log/kube-audit/audit-log.json" -> null
                      - policy     = jsonencode(
                            {
                              - apiVersion = "audit.k8s.io/v1"
                              - kind       = "Policy"
                              - metadata   = {
                                  - creationTimestamp = null
                                }
                              - rules      = [
                                  - {
                                      - level = "Metadata"
                                    },
                                ]
                            }
                        ) -> null
                    }
                }
            }
- upgrade_strategy {
          - drain                        = false -> null
          - max_unavailable_controlplane = "1" -> null
          - max_unavailable_worker       = "10%" -> null
        }
```

update_strategy (**should be fixed with PR above**) and audit_log aren't defined by us anywhere in the config, but cluster_cidr is:
```
services {
    kube_api {
      service_cluster_ip_range = "172.21.0.0/16"
    }

    kube_controller {
      cluster_cidr             = "172.20.0.0/16"
      service_cluster_ip_range = "172.21.0.0/16"
    }
    kubelet {
      cluster_domain     = "cluster.local"
      cluster_dns_server = "172.21.0.10"
    }
  }
```

**Comment by rawmind0** [comment] 2020-04-09 17:00
Updated PR to include `audit_log`

**Comment by raroldan** [comment] 2020-04-29 08:08
Can confirm PR #191 fixes the issue.

**Comment by rawmind0** [comment] 2020-05-06 14:10
PR merger into master. Please reopen issue if needed.

**Closed by rawmind0** 2020-05-06 14:10 UTC
