### ISSUE TITLE
[Feature request] RKE 1.3.0 is not available through terraform yet

### ISSUE THREAD

**Issue by hutm** [rancher/terraform-provider-rke#308] opened 2021-08-31 23:26 UTC
Would be super cool to have RKE 1.3.0 that was recently released here https://github.com/rancher/rke/releases/tag/v1.3.0

**Comment by belgaied2** [comment] 2021-09-16 13:58
I am pushing this issue because of the following need:
Creating RKE cluster using the Terraform provider and a bastion server that has proxy environment variables set.
The problem is solved upstream after fixing [this issue](https://github.com/rancher/rke/issues/2525), using a flag `ignore_proxy_env_vars: true` which should also be implemented in the Terraform provider for RKE.

**Comment by rgl** [comment] 2021-09-21 12:05
Can this project be keep in sync with the rke releases?

**Comment by rawmind0** [comment] 2021-09-21 17:21
RKE v1.3.1 will be supported on next tfp release, PR #310

**Comment by rgl** [comment] 2021-09-21 17:47
Nice! Thank You!

What is a `tfp release`?

**Comment by muhlba91** [comment] 2021-11-05 15:35
any information on that one already (about 1.5 months later)?
we are blocked due to needing k8s 1.21, and, hence, RKE v1.3.x support not getting into the TF provider.

**Comment by janosmiko** [comment] 2021-11-10 08:22
+1 it would be great to have possibility to support k8s 1.21

**Comment by debackerl** [comment] 2021-12-08 12:22
Is terraform-provider-rke still recommended? Today, the most recent kubernetes that can be installed through this provider is 1.20 (released in Dec 2020). End of life is Feb 28th 2022, so we have 2 months an 20 days to migrate.

1.22 released August 2021 isn't available, neither is 1.21 released in May 2021.

I think this is a great piece of software, and I'm grateful to Rancher for sharing this. However, from an operation point of view, the situation is not tenable. I can't migrate a cluster in just a few weeks, while 1.21 was in fact available in May, and we are now 2 versions behind.

**Comment by rawmind0** [comment] 2021-12-20 13:38
RKE 1.3.3 supported on new tfp release v1.3.0

**Closed by rawmind0** 2021-12-20 13:38 UTC
Labels: team/area2

**Comment by hutm** [comment] 2021-12-20 19:51
@rawmind0 thanks for pushing this forward! Long awaited release!
