### ISSUE TITLE
Dynamic nodes: Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by jshrack-ssi** [rancher/terraform-provider-rke#167] opened 2020-02-08 16:25 UTC
I am seeing the following error (inconsistently) when employing RKE dynamic nodes on the first terraform apply:

Error: Provider produced inconsistent final plan

When expanding the plan for rke_cluster.rancher_server to include new values
learned so far during apply, provider "registry.terraform.io/-/rke" produced
an invalid new value for .nodes: block count changed from 2 to 6.

A subsequent apply will properly recognize all nodes. Here is my RKE plan:

############################
###########################

resource "rke_cluster" "rancher_server" {
  depends_on = [null_resource.wait_for_docker]

  dynamic nodes {
    for_each = local.master_instances_ips
    content {
      address          = nodes.value.private_ip
      user             = var.instance_ssh_user
      role             = ["controlplane", "etcd"]
      ssh_key          = file(var.aws_key_pair_private_key)
      port             = var.instance_ssh_port
    }
  }

  dynamic nodes {
    for_each = local.worker_instances_ips
    content {
      address          = nodes.value.private_ip
      user             = var.instance_ssh_user
      role             = ["worker"]
      ssh_key          = file(var.aws_key_pair_private_key)
      port             = var.instance_ssh_port
    }
  }

  cluster_name = var.rke_cluster_cluster_name
  addons       = file("${path.module}/files/addons.yaml")

  kubernetes_version = var.rke_cluster_kubernetes_version

  authentication {
    strategy = "x509"

    sans = [
      local.api_server_hostname
    ]
  }

  cloud_provider {
    name = "aws"
    aws_cloud_provider {
      global {
        disable_security_group_ingress = false
        disable_strict_zone_check      = false
      }
    }
  }

  network {
    plugin = var.rke_cluster_kubernetes_network_plugin
  }

  services {
    etcd {
      # for etcd snapshots
      backup_config {
        interval_hours = var.rke_cluster_services_etcd_backup_config_interval_hours
        retention      = var.rke_cluster_services_etcd_backup_config_retention
        # s3 specific parameters
        s3_backup_config {
          # access_key  = aws_iam_access_key.etcd_backup_user.id
          # secret_key  = aws_iam_access_key.etcd_backup_user.secret
          bucket_name = aws_s3_bucket.etcd_backups.id
          region      = local.rke_backup_region
          endpoint    = local.rke_backup_endpoint
        }
      }
    }
    kube_api {
      extra_args = var.rke_cluster_services_kube_api_extra_args
    }
    kubelet {
      extra_args = var.rke_cluster_services_kubelet_extra_args
    }
  }
}

resource "local_file" "rke_cluster_yaml" {
  filename = "${var.rke_cluster_yaml_output_path}/${local.name}-cluster.yaml"
  content = rke_cluster.rancher_server.rke_cluster_yaml
}

resource "local_file" "kube_cluster_yaml" {
  filename = "${var.kubeconfig_output_path}/${local.name}-config"
  content = templatefile("${path.module}/files/kube_config_cluster.yml", {
    api_server_url     = local.api_server_url
    rancher_cluster_ca = base64encode(rke_cluster.rancher_server.ca_crt)
    rancher_user_cert  = base64encode(rke_cluster.rancher_server.client_cert)
    rancher_user_key   = base64encode(rke_cluster.rancher_server.client_key)
  })
}

**Comment by johnceloria** [comment] 2020-02-26 15:04
Duplicate of #112

**Comment by rawmind0** [comment] 2020-03-09 21:09
Supersed #112 .

Submited PR #180 to address this issue. Could you please test it??

**Comment by eugene-dm** [comment] 2020-03-13 10:27
@rawmind0 Could you please share instructions on how to compile the plugin with your PR included. I'm a bit a newbie in GO lang and spent a whole hour trying to compile the right version but with no luck. Thanks.

**Comment by rawmind0** [comment] 2020-03-13 20:42
@eugene-dm , released 1.0.0-rc4 that include fix. 

Please reopen issue if needed.

**Closed by rawmind0** 2020-03-13 20:42 UTC

**Comment by ashish-shiftright** [comment] 2020-06-16 00:48
I ran into this issue today. And I am using released version v1.0.0.

Error: Provider produced inconsistent final plan
When expanding the plan for module.rancher_server.rke_cluster.rancher_server
to include new values learned so far during apply, provider
"registry.terraform.io/-/rke" produced an invalid new value for .nodes: block
count changed from 4 to 6.
This is a bug in the provider, which should be reported in the provider's own
issue tracker.

**Comment by rawmind0** [comment] 2020-06-16 08:54
@ashish-shiftright , what terraform module are you using?? I'm seeing `registry.terraform.io/-/rke` on you message but this provider is not published on `registry.terraform.io` yet.

**Comment by ashish-shiftright** [comment] 2020-06-16 16:40
I got the binary from here = https://github.com/rancher/terraform-provider-rke/releases/tag/1.0.0

Another update - It always fails with the error for the first time. But it works if I just re-run terraform apply second time.

**Comment by rawmind0** [comment] 2020-06-16 16:52
> "registry.terraform.io/-/rke" produced an invalid new value for .nodes: block
count changed from 4 to 6.

I mean this message, referencing `registry.terraform.io/-/rke`

How looks like your tf file??

**Comment by kubaracek** [comment] 2020-06-23 12:46
I'm running into the same error. Mine is referencing the same `registry.terraform.io/-/rke` thing but I've got it in my ./terraform/ plugins folder

**Comment by julienym** [comment] 2020-10-21 15:20
Reopen with: https://github.com/rancher/terraform-provider-rke/issues/257
