### ISSUE TITLE
`rke_cluster_yaml` output not fully populated on first apply

### ISSUE THREAD

**Issue by mouellet** [rancher/terraform-provider-rke#326] opened 2022-01-31 14:29 UTC
The `rke_cluster_yaml` output is missing some computed values on the first execution and a second execution is required to have and idempotent output. Specifically, the services image and extra_env values. 

### Steps to Reproduce
1. add the `rke_cluster_yaml` attribute as output (nonsensitive maybe required for debugging)
2. run `terraform apply`
3. run `terraform plan`

### Expected Behaviour
The `terraform plan` command should show no changes to infrastructure (i.e. no change to the `rke_cluster_yaml` output).

### Actual Behaviour
The `terraform plan` command shows changes to the `rke_cluster_yaml`. Sample:
```
Changes to Outputs:
  ~ rke_cluster_yaml = <<-EOT
        services:
          etcd:
      -     image: ""
      +     image: (redacted)/rancher/mirrored-coreos-etcd:v3.4.15-rancher1
          kube-api:
      -     extra_env: []
      +     extra_env:
      +     - RKE_CLOUD_CONFIG_CHECKSUM=(redacted)
      +     - RKE_AUDITLOG_CONFIG_CHECKSUM=(redacted)
      +     - RKE_CLOUD_CONFIG_CHECKSUM=(redacted)
      +     - RKE_AUDITLOG_CONFIG_CHECKSUM=(redacted)
      +     - RKE_CLOUD_CONFIG_CHECKSUM=(redacted)
      +     - RKE_AUDITLOG_CONFIG_CHECKSUM=(redacted)
      +     - RKE_CLOUD_CONFIG_CHECKSUM=(redacted)
      +     - RKE_AUDITLOG_CONFIG_CHECKSUM=(redacted)
      +     - RKE_CLOUD_CONFIG_CHECKSUM=(redacted)
      +     - RKE_AUDITLOG_CONFIG_CHECKSUM=(redacted)
      +     - RKE_CLOUD_CONFIG_CHECKSUM=(redacted)
      +     - RKE_AUDITLOG_CONFIG_CHECKSUM=(redacted)
      -     image: ""
      +     image: (redacted)/rancher/hyperkube:v1.20.13-rancher1
          kube-controller:
      -     extra_env: []
      +     extra_env:
      +     - RKE_CLOUD_CONFIG_CHECKSUM=(redacted)
      +     - RKE_CLOUD_CONFIG_CHECKSUM=(redacted)
      +     - RKE_CLOUD_CONFIG_CHECKSUM=(redacted)
      +     - RKE_CLOUD_CONFIG_CHECKSUM=(redacted)
      +     - RKE_CLOUD_CONFIG_CHECKSUM=(redacted)
      +     - RKE_CLOUD_CONFIG_CHECKSUM=(redacted)
      -     image: ""
      +     image: (redacted)/rancher/hyperkube:v1.20.13-rancher1
          kubelet:
      -     image: ""
      +     image: (redacted)/rancher/hyperkube:v1.20.13-rancher1
      -     infra_container_image: ""
      +     infra_container_image: (redacted)/rancher/mirrored-pause:3.2
          kubeproxy:
      -     image: ""
      +     image: (redacted)/rancher/hyperkube:v1.20.13-rancher1
          scheduler:
      -     image: ""
      +     image: (redacted)/rancher/hyperkube:v1.20.13-rancher1
    EOT
```

**Comment by annablender** [comment] 2022-04-13 13:44
I was not able to reproduce this issue.

RKE config
```
# set path to ssh private key so we can ssh into each node for provisioning. If aws ec2 should point to your aws public key
ssh_key_path: ~/.ssh/ablender-rke-key.pem

# kubernetes_version is not required can leave blank or comment out and will use latest
kubernetes_version:

# list of nodes including internal addresses is strongly recommended. user must be set to ubuntu for example for ubuntu ec2 instances for ssh access.
# if your AWS AMI is not ubuntu like centos, rocky linux, etc the username is usually (but not always) ec2-user
# role must be defined - here we specify all three roles per each node. However technically minimums just are: etcd 3 nodes, controlplane 2 nodes, worker 2 nodes for minimal fault tolerance
nodes:
  - address: 3.23.132.119
    internal_address: 172.31.47.64
    user: ec2-user
    role: [etcd, controlplane, worker]
  - address: 13.59.142.7
    internal_address: 172.31.44.84
    user: ec2-user
    role: [etcd, controlplane, worker]

services:
    kubelet:
        image: rancher/hyperkube:v1.20.13-rancher1
        extra_env:
        - "HTTP_PROXY=http://test_proxy"
        - "NO_PROXY=true"
```

Terraform config
```
# Use the rancher/rke Terraform provider
terraform {
  required_providers {
    rke = {
      source = "rancher/rke"
      version = "1.3.0"
    }
  }
}

# Configure RKE provider
provider "rke" {
  log_file = "rke_debug.log"
}

# Create a new RKE cluster using config yaml
resource "rke_cluster" "foo" {
  cluster_yaml = file("cluster.yml")
}
```

`terraform apply`
![image](https://user-images.githubusercontent.com/12955547/163194216-e413f70c-3462-43f5-b60c-672cee117c14.png)

`terraform plan`
![image](https://user-images.githubusercontent.com/12955547/163194283-554f1742-a3c3-4cfb-93f8-6cf402c5c3c0.png)

@mouellet If you can, please share the RKE config that you used to get the above results. However, I reviewed the code and a call to `expandRKECluster` is missing so I tested deploying an RKE cluster through terraform with that code and it works fine. I'll submit a PR with the change.

**Comment by mouellet** [comment] 2022-04-13 15:37
Hi @annablender,

I did have a `private_registries` set in my cluster.yaml...

Also, I've already made a PR for this! See: #327

**Comment by annablender** [comment] 2022-04-13 15:59
@mouellet If you could post your `cluster.yaml` that would be very helpful! I thought you were merging into `rancher/rancher` never mind, it's in the terraform provider. Just merged.

**Comment by annablender** [comment] 2022-04-14 15:49
## Testing template

#### Root cause

Need more details on original reproduction to see the results from `terraform plan` but code to expand RKE configuration values was not being run in general.
 
#### What was fixed, or what changes have occurred

* Added missing call to `expandRKECluster` in the terraform provider https://github.com/rancher/terraform-provider-rke/blob/9244cd3d71ada7669ef78bee8029b404b19e2f62/rke/structure_rke_cluster.go#L229

#### Areas or cases that should be tested

* Create 2 EC2 nodes and provision them for RKE
* Create RKE config
* Create terraform config file with `rke_cluster_yaml` specifying path to your RKE config
* Run `terraform apply`
* Run `terraform plan` and make sure no values are auto overwritten by terraform.
 
#### What areas could experience regressions ?

N/A
 
#### Are the repro steps accurate/minimal ?

**Comment by timhaneunsoo** [comment] 2022-05-02 18:07
### Testing: ###

Tested with the steps given in testing template and previous comments for file configuration.

**Result**
I was also unable to reproduce the issue, but after adding the extra environment variables in the rke config.yaml file, I saw that no values were auto overwritten

![image.png](https://zube.io/files/rancher/b48051c0a7472a75fcab44b9551303ae-image.png)

**Closed by timhaneunsoo** 2022-05-02 18:07 UTC
Labels: [zube]: QA Working, team/area2, QA/XS
